/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// Policy information returned after the policy is successfully created.
    /// </summary>
    [DataContract]
    public partial class AIHubCreateData :  IEquatable<AIHubCreateData>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets StrategyType
        /// </summary>
        [DataMember(Name="strategy_type")]
        public StrategyType StrategyType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AIHubCreateData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AIHubCreateData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AIHubCreateData" /> class.
        /// </summary>
        /// <param name="strategyId">strategyId (required).</param>
        /// <param name="strategyType">strategyType (required).</param>
        /// <param name="market">market (required).</param>
        /// <param name="status">The initial state after successful creation, usually &#x60;running&#x60; (required).</param>
        /// <param name="jumpUrl">jumpUrl.</param>
        public AIHubCreateData(string strategyId = default(string), StrategyType strategyType = default(StrategyType), string market = default(string), string status = default(string), string jumpUrl = default(string))
        {
            // to ensure "strategyId" is required (not null)
            this.StrategyId = strategyId ?? throw new ArgumentNullException("strategyId", "strategyId is a required property for AIHubCreateData and cannot be null");
            this.StrategyType = strategyType;
            // to ensure "market" is required (not null)
            this.Market = market ?? throw new ArgumentNullException("market", "market is a required property for AIHubCreateData and cannot be null");
            // to ensure "status" is required (not null)
            this.Status = status ?? throw new ArgumentNullException("status", "status is a required property for AIHubCreateData and cannot be null");
            this.JumpUrl = jumpUrl;
        }

        /// <summary>
        /// Gets or Sets StrategyId
        /// </summary>
        [DataMember(Name="strategy_id")]
        public string StrategyId { get; set; }

        /// <summary>
        /// Gets or Sets Market
        /// </summary>
        [DataMember(Name="market")]
        public string Market { get; set; }

        /// <summary>
        /// The initial state after successful creation, usually &#x60;running&#x60;
        /// </summary>
        /// <value>The initial state after successful creation, usually &#x60;running&#x60;</value>
        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets JumpUrl
        /// </summary>
        [DataMember(Name="jump_url")]
        public string JumpUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AIHubCreateData {\n");
            sb.Append("  StrategyId: ").Append(StrategyId).Append("\n");
            sb.Append("  StrategyType: ").Append(StrategyType).Append("\n");
            sb.Append("  Market: ").Append(Market).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  JumpUrl: ").Append(JumpUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AIHubCreateData);
        }

        /// <summary>
        /// Returns true if AIHubCreateData instances are equal
        /// </summary>
        /// <param name="input">Instance of AIHubCreateData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AIHubCreateData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StrategyId == input.StrategyId ||
                    (this.StrategyId != null &&
                    this.StrategyId.Equals(input.StrategyId))
                ) && 
                (
                    this.StrategyType == input.StrategyType ||
                    this.StrategyType.Equals(input.StrategyType)
                ) && 
                (
                    this.Market == input.Market ||
                    (this.Market != null &&
                    this.Market.Equals(input.Market))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.JumpUrl == input.JumpUrl ||
                    (this.JumpUrl != null &&
                    this.JumpUrl.Equals(input.JumpUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StrategyId != null)
                    hashCode = hashCode * 59 + this.StrategyId.GetHashCode();
                hashCode = hashCode * 59 + this.StrategyType.GetHashCode();
                if (this.Market != null)
                    hashCode = hashCode * 59 + this.Market.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.JumpUrl != null)
                    hashCode = hashCode * 59 + this.JumpUrl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
