/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// A single record in the list of running policies.
    /// </summary>
    [DataContract]
    public partial class AIHubPortfolioRunningItem :  IEquatable<AIHubPortfolioRunningItem>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets StrategyType
        /// </summary>
        [DataMember(Name="strategy_type")]
        public StrategyType StrategyType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AIHubPortfolioRunningItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AIHubPortfolioRunningItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AIHubPortfolioRunningItem" /> class.
        /// </summary>
        /// <param name="strategyId">strategyId (required).</param>
        /// <param name="strategyType">strategyType (required).</param>
        /// <param name="strategyName">strategyName (required).</param>
        /// <param name="market">market (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="pnl">pnl.</param>
        /// <param name="pnlRate">pnlRate.</param>
        /// <param name="investAmount">investAmount.</param>
        /// <param name="createdAt">Created time.</param>
        public AIHubPortfolioRunningItem(string strategyId = default(string), StrategyType strategyType = default(StrategyType), string strategyName = default(string), string market = default(string), string status = default(string), string pnl = default(string), string pnlRate = default(string), string investAmount = default(string), string createdAt = default(string))
        {
            // to ensure "strategyId" is required (not null)
            this.StrategyId = strategyId ?? throw new ArgumentNullException("strategyId", "strategyId is a required property for AIHubPortfolioRunningItem and cannot be null");
            this.StrategyType = strategyType;
            // to ensure "strategyName" is required (not null)
            this.StrategyName = strategyName ?? throw new ArgumentNullException("strategyName", "strategyName is a required property for AIHubPortfolioRunningItem and cannot be null");
            // to ensure "market" is required (not null)
            this.Market = market ?? throw new ArgumentNullException("market", "market is a required property for AIHubPortfolioRunningItem and cannot be null");
            // to ensure "status" is required (not null)
            this.Status = status ?? throw new ArgumentNullException("status", "status is a required property for AIHubPortfolioRunningItem and cannot be null");
            this.Pnl = pnl;
            this.PnlRate = pnlRate;
            this.InvestAmount = investAmount;
            this.CreatedAt = createdAt;
        }

        /// <summary>
        /// Gets or Sets StrategyId
        /// </summary>
        [DataMember(Name="strategy_id")]
        public string StrategyId { get; set; }

        /// <summary>
        /// Gets or Sets StrategyName
        /// </summary>
        [DataMember(Name="strategy_name")]
        public string StrategyName { get; set; }

        /// <summary>
        /// Gets or Sets Market
        /// </summary>
        [DataMember(Name="market")]
        public string Market { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Pnl
        /// </summary>
        [DataMember(Name="pnl")]
        public string Pnl { get; set; }

        /// <summary>
        /// Gets or Sets PnlRate
        /// </summary>
        [DataMember(Name="pnl_rate")]
        public string PnlRate { get; set; }

        /// <summary>
        /// Gets or Sets InvestAmount
        /// </summary>
        [DataMember(Name="invest_amount")]
        public string InvestAmount { get; set; }

        /// <summary>
        /// Created time
        /// </summary>
        /// <value>Created time</value>
        [DataMember(Name="created_at")]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AIHubPortfolioRunningItem {\n");
            sb.Append("  StrategyId: ").Append(StrategyId).Append("\n");
            sb.Append("  StrategyType: ").Append(StrategyType).Append("\n");
            sb.Append("  StrategyName: ").Append(StrategyName).Append("\n");
            sb.Append("  Market: ").Append(Market).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Pnl: ").Append(Pnl).Append("\n");
            sb.Append("  PnlRate: ").Append(PnlRate).Append("\n");
            sb.Append("  InvestAmount: ").Append(InvestAmount).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AIHubPortfolioRunningItem);
        }

        /// <summary>
        /// Returns true if AIHubPortfolioRunningItem instances are equal
        /// </summary>
        /// <param name="input">Instance of AIHubPortfolioRunningItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AIHubPortfolioRunningItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StrategyId == input.StrategyId ||
                    (this.StrategyId != null &&
                    this.StrategyId.Equals(input.StrategyId))
                ) && 
                (
                    this.StrategyType == input.StrategyType ||
                    this.StrategyType.Equals(input.StrategyType)
                ) && 
                (
                    this.StrategyName == input.StrategyName ||
                    (this.StrategyName != null &&
                    this.StrategyName.Equals(input.StrategyName))
                ) && 
                (
                    this.Market == input.Market ||
                    (this.Market != null &&
                    this.Market.Equals(input.Market))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Pnl == input.Pnl ||
                    (this.Pnl != null &&
                    this.Pnl.Equals(input.Pnl))
                ) && 
                (
                    this.PnlRate == input.PnlRate ||
                    (this.PnlRate != null &&
                    this.PnlRate.Equals(input.PnlRate))
                ) && 
                (
                    this.InvestAmount == input.InvestAmount ||
                    (this.InvestAmount != null &&
                    this.InvestAmount.Equals(input.InvestAmount))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StrategyId != null)
                    hashCode = hashCode * 59 + this.StrategyId.GetHashCode();
                hashCode = hashCode * 59 + this.StrategyType.GetHashCode();
                if (this.StrategyName != null)
                    hashCode = hashCode * 59 + this.StrategyName.GetHashCode();
                if (this.Market != null)
                    hashCode = hashCode * 59 + this.Market.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Pnl != null)
                    hashCode = hashCode * 59 + this.Pnl.GetHashCode();
                if (this.PnlRate != null)
                    hashCode = hashCode * 59 + this.PnlRate.GetHashCode();
                if (this.InvestAmount != null)
                    hashCode = hashCode * 59 + this.InvestAmount.GetHashCode();
                if (this.CreatedAt != null)
                    hashCode = hashCode * 59 + this.CreatedAt.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
