/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// ErrCodeMsg
    /// </summary>
    [DataContract]
    public partial class ErrCodeMsg :  IEquatable<ErrCodeMsg>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrCodeMsg" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ErrCodeMsg() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrCodeMsg" /> class.
        /// </summary>
        /// <param name="code">Error code (required).</param>
        /// <param name="message">Error message (required).</param>
        /// <param name="extra">Additional information (required).</param>
        public ErrCodeMsg(int code = default(int), string message = default(string), Object extra = default(Object))
        {
            this.Code = code;
            // to ensure "message" is required (not null)
            this.Message = message ?? throw new ArgumentNullException("message", "message is a required property for ErrCodeMsg and cannot be null");
            // to ensure "extra" is required (not null)
            this.Extra = extra ?? throw new ArgumentNullException("extra", "extra is a required property for ErrCodeMsg and cannot be null");
        }

        /// <summary>
        /// Error code
        /// </summary>
        /// <value>Error code</value>
        [DataMember(Name="code")]
        public int Code { get; set; }

        /// <summary>
        /// Error message
        /// </summary>
        /// <value>Error message</value>
        [DataMember(Name="message")]
        public string Message { get; set; }

        /// <summary>
        /// Additional information
        /// </summary>
        /// <value>Additional information</value>
        [DataMember(Name="extra")]
        public Object Extra { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ErrCodeMsg {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Extra: ").Append(Extra).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ErrCodeMsg);
        }

        /// <summary>
        /// Returns true if ErrCodeMsg instances are equal
        /// </summary>
        /// <param name="input">Instance of ErrCodeMsg to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ErrCodeMsg input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    this.Code.Equals(input.Code)
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.Extra == input.Extra ||
                    (this.Extra != null &&
                    this.Extra.Equals(input.Extra))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.Extra != null)
                    hashCode = hashCode * 59 + this.Extra.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
