/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// Product configuration
    /// </summary>
    [DataContract]
    public partial class FixedTermProductInfo :  IEquatable<FixedTermProductInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FixedTermProductInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FixedTermProductInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FixedTermProductInfo" /> class.
        /// </summary>
        /// <param name="preRedeem">Whether early redemption is supported: 0 for not supported, 1 for supported (required).</param>
        /// <param name="reinvest">Whether auto-renewal is supported: 0 for not supported, 1 for supported (required).</param>
        /// <param name="redeemAccount">Redemption payout account type (required).</param>
        /// <param name="minVip">Minimum VIP level requirement, 0 means no restriction (required).</param>
        /// <param name="maxVip">Maximum VIP level requirement, 0 means no restriction (required).</param>
        public FixedTermProductInfo(int preRedeem = default(int), int reinvest = default(int), int redeemAccount = default(int), int minVip = default(int), int maxVip = default(int))
        {
            this.PreRedeem = preRedeem;
            this.Reinvest = reinvest;
            this.RedeemAccount = redeemAccount;
            this.MinVip = minVip;
            this.MaxVip = maxVip;
        }

        /// <summary>
        /// Whether early redemption is supported: 0 for not supported, 1 for supported
        /// </summary>
        /// <value>Whether early redemption is supported: 0 for not supported, 1 for supported</value>
        [DataMember(Name="pre_redeem")]
        public int PreRedeem { get; set; }

        /// <summary>
        /// Whether auto-renewal is supported: 0 for not supported, 1 for supported
        /// </summary>
        /// <value>Whether auto-renewal is supported: 0 for not supported, 1 for supported</value>
        [DataMember(Name="reinvest")]
        public int Reinvest { get; set; }

        /// <summary>
        /// Redemption payout account type
        /// </summary>
        /// <value>Redemption payout account type</value>
        [DataMember(Name="redeem_account")]
        public int RedeemAccount { get; set; }

        /// <summary>
        /// Minimum VIP level requirement, 0 means no restriction
        /// </summary>
        /// <value>Minimum VIP level requirement, 0 means no restriction</value>
        [DataMember(Name="min_vip")]
        public int MinVip { get; set; }

        /// <summary>
        /// Maximum VIP level requirement, 0 means no restriction
        /// </summary>
        /// <value>Maximum VIP level requirement, 0 means no restriction</value>
        [DataMember(Name="max_vip")]
        public int MaxVip { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FixedTermProductInfo {\n");
            sb.Append("  PreRedeem: ").Append(PreRedeem).Append("\n");
            sb.Append("  Reinvest: ").Append(Reinvest).Append("\n");
            sb.Append("  RedeemAccount: ").Append(RedeemAccount).Append("\n");
            sb.Append("  MinVip: ").Append(MinVip).Append("\n");
            sb.Append("  MaxVip: ").Append(MaxVip).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FixedTermProductInfo);
        }

        /// <summary>
        /// Returns true if FixedTermProductInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of FixedTermProductInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FixedTermProductInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PreRedeem == input.PreRedeem ||
                    this.PreRedeem.Equals(input.PreRedeem)
                ) && 
                (
                    this.Reinvest == input.Reinvest ||
                    this.Reinvest.Equals(input.Reinvest)
                ) && 
                (
                    this.RedeemAccount == input.RedeemAccount ||
                    this.RedeemAccount.Equals(input.RedeemAccount)
                ) && 
                (
                    this.MinVip == input.MinVip ||
                    this.MinVip.Equals(input.MinVip)
                ) && 
                (
                    this.MaxVip == input.MaxVip ||
                    this.MaxVip.Equals(input.MaxVip)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.PreRedeem.GetHashCode();
                hashCode = hashCode * 59 + this.Reinvest.GetHashCode();
                hashCode = hashCode * 59 + this.RedeemAccount.GetHashCode();
                hashCode = hashCode * 59 + this.MinVip.GetHashCode();
                hashCode = hashCode * 59 + this.MaxVip.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
