/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// FlashSwapMultiCurrencyManyToOneOrderPreviewReq
    /// </summary>
    [DataContract]
    public partial class FlashSwapMultiCurrencyManyToOneOrderPreviewReq :  IEquatable<FlashSwapMultiCurrencyManyToOneOrderPreviewReq>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FlashSwapMultiCurrencyManyToOneOrderPreviewReq" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FlashSwapMultiCurrencyManyToOneOrderPreviewReq() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FlashSwapMultiCurrencyManyToOneOrderPreviewReq" /> class.
        /// </summary>
        /// <param name="_params">Multi-currency exchange preview parameter list (required).</param>
        public FlashSwapMultiCurrencyManyToOneOrderPreviewReq(List<FlashSwapMultiCurrencyPreviewParam> _params = default(List<FlashSwapMultiCurrencyPreviewParam>))
        {
            // to ensure "_params" is required (not null)
            this.Params = _params ?? throw new ArgumentNullException("_params", "_params is a required property for FlashSwapMultiCurrencyManyToOneOrderPreviewReq and cannot be null");
        }

        /// <summary>
        /// Multi-currency exchange preview parameter list
        /// </summary>
        /// <value>Multi-currency exchange preview parameter list</value>
        [DataMember(Name="params")]
        public List<FlashSwapMultiCurrencyPreviewParam> Params { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FlashSwapMultiCurrencyManyToOneOrderPreviewReq {\n");
            sb.Append("  Params: ").Append(Params).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FlashSwapMultiCurrencyManyToOneOrderPreviewReq);
        }

        /// <summary>
        /// Returns true if FlashSwapMultiCurrencyManyToOneOrderPreviewReq instances are equal
        /// </summary>
        /// <param name="input">Instance of FlashSwapMultiCurrencyManyToOneOrderPreviewReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FlashSwapMultiCurrencyManyToOneOrderPreviewReq input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Params == input.Params ||
                    this.Params != null &&
                    input.Params != null &&
                    this.Params.SequenceEqual(input.Params)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Params != null)
                    hashCode = hashCode * 59 + this.Params.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
