/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// FuturesADLRiskStates
    /// </summary>
    [DataContract]
    public partial class FuturesADLRiskStates :  IEquatable<FuturesADLRiskStates>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FuturesADLRiskStates" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FuturesADLRiskStates() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FuturesADLRiskStates" /> class.
        /// </summary>
        /// <param name="settle">Settle currency (required).</param>
        /// <param name="states">Mapping of futures markets to ADL risk states (required).</param>
        public FuturesADLRiskStates(string settle = default(string), Dictionary<string, FuturesADLRiskState> states = default(Dictionary<string, FuturesADLRiskState>))
        {
            // to ensure "settle" is required (not null)
            this.Settle = settle ?? throw new ArgumentNullException("settle", "settle is a required property for FuturesADLRiskStates and cannot be null");
            // to ensure "states" is required (not null)
            this.States = states ?? throw new ArgumentNullException("states", "states is a required property for FuturesADLRiskStates and cannot be null");
        }

        /// <summary>
        /// Settle currency
        /// </summary>
        /// <value>Settle currency</value>
        [DataMember(Name="settle")]
        public string Settle { get; set; }

        /// <summary>
        /// Mapping of futures markets to ADL risk states
        /// </summary>
        /// <value>Mapping of futures markets to ADL risk states</value>
        [DataMember(Name="states")]
        public Dictionary<string, FuturesADLRiskState> States { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FuturesADLRiskStates {\n");
            sb.Append("  Settle: ").Append(Settle).Append("\n");
            sb.Append("  States: ").Append(States).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FuturesADLRiskStates);
        }

        /// <summary>
        /// Returns true if FuturesADLRiskStates instances are equal
        /// </summary>
        /// <param name="input">Instance of FuturesADLRiskStates to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FuturesADLRiskStates input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Settle == input.Settle ||
                    (this.Settle != null &&
                    this.Settle.Equals(input.Settle))
                ) && 
                (
                    this.States == input.States ||
                    this.States != null &&
                    input.States != null &&
                    this.States.SequenceEqual(input.States)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Settle != null)
                    hashCode = hashCode * 59 + this.Settle.GetHashCode();
                if (this.States != null)
                    hashCode = hashCode * 59 + this.States.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
