/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// InlineResponse20044
    /// </summary>
    [DataContract]
    public partial class InlineResponse20044 :  IEquatable<InlineResponse20044>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20044" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse20044() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20044" /> class.
        /// </summary>
        /// <param name="id">Account Change Record ID (required).</param>
        /// <param name="userId">User ID (required).</param>
        /// <param name="businessId">Business ID (required).</param>
        /// <param name="type">变更类型| &#x60;TRANSACTION&#x60; 成交 &#x60;TRADING_FEE&#x60; 手续费 &#x60;FUNDING_FEE&#x60; 合约资金费 &#x60;LIQUIDATION_FEE&#x60; 强平费 &#x60;TRANSFER_IN&#x60; 资金转入 &#x60;TRANSFER_OUT&#x60; 资金转出 &#x60;BANKRUPT_COMPENSATION&#x60; 穿仓补贴 &#x60;AUTO_REPAY&#x60; 杠杆仓位自动还负债 (required).</param>
        /// <param name="exchangeType">Exchange (required).</param>
        /// <param name="coin">Currency (required).</param>
        /// <param name="change">Change amount (positive indicates transfer in; negative indicates transfer out) (required).</param>
        /// <param name="balance">Balance after change (required).</param>
        /// <param name="createTime">Created time (required).</param>
        public InlineResponse20044(string id = default(string), string userId = default(string), string businessId = default(string), string type = default(string), string exchangeType = default(string), string coin = default(string), string change = default(string), string balance = default(string), string createTime = default(string))
        {
            // to ensure "id" is required (not null)
            this.Id = id ?? throw new ArgumentNullException("id", "id is a required property for InlineResponse20044 and cannot be null");
            // to ensure "userId" is required (not null)
            this.UserId = userId ?? throw new ArgumentNullException("userId", "userId is a required property for InlineResponse20044 and cannot be null");
            // to ensure "businessId" is required (not null)
            this.BusinessId = businessId ?? throw new ArgumentNullException("businessId", "businessId is a required property for InlineResponse20044 and cannot be null");
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type", "type is a required property for InlineResponse20044 and cannot be null");
            // to ensure "exchangeType" is required (not null)
            this.ExchangeType = exchangeType ?? throw new ArgumentNullException("exchangeType", "exchangeType is a required property for InlineResponse20044 and cannot be null");
            // to ensure "coin" is required (not null)
            this.Coin = coin ?? throw new ArgumentNullException("coin", "coin is a required property for InlineResponse20044 and cannot be null");
            // to ensure "change" is required (not null)
            this.Change = change ?? throw new ArgumentNullException("change", "change is a required property for InlineResponse20044 and cannot be null");
            // to ensure "balance" is required (not null)
            this.Balance = balance ?? throw new ArgumentNullException("balance", "balance is a required property for InlineResponse20044 and cannot be null");
            // to ensure "createTime" is required (not null)
            this.CreateTime = createTime ?? throw new ArgumentNullException("createTime", "createTime is a required property for InlineResponse20044 and cannot be null");
        }

        /// <summary>
        /// Account Change Record ID
        /// </summary>
        /// <value>Account Change Record ID</value>
        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// User ID
        /// </summary>
        /// <value>User ID</value>
        [DataMember(Name="user_id")]
        public string UserId { get; set; }

        /// <summary>
        /// Business ID
        /// </summary>
        /// <value>Business ID</value>
        [DataMember(Name="business_id")]
        public string BusinessId { get; set; }

        /// <summary>
        /// 变更类型| &#x60;TRANSACTION&#x60; 成交 &#x60;TRADING_FEE&#x60; 手续费 &#x60;FUNDING_FEE&#x60; 合约资金费 &#x60;LIQUIDATION_FEE&#x60; 强平费 &#x60;TRANSFER_IN&#x60; 资金转入 &#x60;TRANSFER_OUT&#x60; 资金转出 &#x60;BANKRUPT_COMPENSATION&#x60; 穿仓补贴 &#x60;AUTO_REPAY&#x60; 杠杆仓位自动还负债
        /// </summary>
        /// <value>变更类型| &#x60;TRANSACTION&#x60; 成交 &#x60;TRADING_FEE&#x60; 手续费 &#x60;FUNDING_FEE&#x60; 合约资金费 &#x60;LIQUIDATION_FEE&#x60; 强平费 &#x60;TRANSFER_IN&#x60; 资金转入 &#x60;TRANSFER_OUT&#x60; 资金转出 &#x60;BANKRUPT_COMPENSATION&#x60; 穿仓补贴 &#x60;AUTO_REPAY&#x60; 杠杆仓位自动还负债</value>
        [DataMember(Name="type")]
        public string Type { get; set; }

        /// <summary>
        /// Exchange
        /// </summary>
        /// <value>Exchange</value>
        [DataMember(Name="exchange_type")]
        public string ExchangeType { get; set; }

        /// <summary>
        /// Currency
        /// </summary>
        /// <value>Currency</value>
        [DataMember(Name="coin")]
        public string Coin { get; set; }

        /// <summary>
        /// Change amount (positive indicates transfer in; negative indicates transfer out)
        /// </summary>
        /// <value>Change amount (positive indicates transfer in; negative indicates transfer out)</value>
        [DataMember(Name="change")]
        public string Change { get; set; }

        /// <summary>
        /// Balance after change
        /// </summary>
        /// <value>Balance after change</value>
        [DataMember(Name="balance")]
        public string Balance { get; set; }

        /// <summary>
        /// Created time
        /// </summary>
        /// <value>Created time</value>
        [DataMember(Name="create_time")]
        public string CreateTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20044 {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  BusinessId: ").Append(BusinessId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  ExchangeType: ").Append(ExchangeType).Append("\n");
            sb.Append("  Coin: ").Append(Coin).Append("\n");
            sb.Append("  Change: ").Append(Change).Append("\n");
            sb.Append("  Balance: ").Append(Balance).Append("\n");
            sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20044);
        }

        /// <summary>
        /// Returns true if InlineResponse20044 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20044 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20044 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.BusinessId == input.BusinessId ||
                    (this.BusinessId != null &&
                    this.BusinessId.Equals(input.BusinessId))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.ExchangeType == input.ExchangeType ||
                    (this.ExchangeType != null &&
                    this.ExchangeType.Equals(input.ExchangeType))
                ) && 
                (
                    this.Coin == input.Coin ||
                    (this.Coin != null &&
                    this.Coin.Equals(input.Coin))
                ) && 
                (
                    this.Change == input.Change ||
                    (this.Change != null &&
                    this.Change.Equals(input.Change))
                ) && 
                (
                    this.Balance == input.Balance ||
                    (this.Balance != null &&
                    this.Balance.Equals(input.Balance))
                ) && 
                (
                    this.CreateTime == input.CreateTime ||
                    (this.CreateTime != null &&
                    this.CreateTime.Equals(input.CreateTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.BusinessId != null)
                    hashCode = hashCode * 59 + this.BusinessId.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.ExchangeType != null)
                    hashCode = hashCode * 59 + this.ExchangeType.GetHashCode();
                if (this.Coin != null)
                    hashCode = hashCode * 59 + this.Coin.GetHashCode();
                if (this.Change != null)
                    hashCode = hashCode * 59 + this.Change.GetHashCode();
                if (this.Balance != null)
                    hashCode = hashCode * 59 + this.Balance.GetHashCode();
                if (this.CreateTime != null)
                    hashCode = hashCode * 59 + this.CreateTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
