/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// InlineResponse20022Data
    /// </summary>
    [DataContract]
    public partial class InlineResponse20022Data :  IEquatable<InlineResponse20022Data>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20022Data" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse20022Data() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20022Data" /> class.
        /// </summary>
        /// <param name="sRVTM">Timestamp when message was successfully sent (current timestamp) (required).</param>
        public InlineResponse20022Data(int sRVTM = default(int))
        {
            this.SRVTM = sRVTM;
        }

        /// <summary>
        /// Timestamp when message was successfully sent (current timestamp)
        /// </summary>
        /// <value>Timestamp when message was successfully sent (current timestamp)</value>
        [DataMember(Name="SRVTM")]
        public int SRVTM { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20022Data {\n");
            sb.Append("  SRVTM: ").Append(SRVTM).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20022Data);
        }

        /// <summary>
        /// Returns true if InlineResponse20022Data instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20022Data to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20022Data input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SRVTM == input.SRVTM ||
                    this.SRVTM.Equals(input.SRVTM)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.SRVTM.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
