/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// InlineResponse20027
    /// </summary>
    [DataContract]
    public partial class InlineResponse20027 :  IEquatable<InlineResponse20027>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20027" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse20027() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20027" /> class.
        /// </summary>
        /// <param name="quoteId">Quote ID (required).</param>
        /// <param name="validMs">Valid time (milliseconds timestamp) (required).</param>
        /// <param name="fromCoin">Asset Sold (required).</param>
        /// <param name="toCoin">Asset Bought (required).</param>
        /// <param name="fromAmount">Amount to sell (required).</param>
        /// <param name="toAmount">Amount to buy (required).</param>
        /// <param name="price">Price (required).</param>
        public InlineResponse20027(string quoteId = default(string), string validMs = default(string), string fromCoin = default(string), string toCoin = default(string), string fromAmount = default(string), string toAmount = default(string), string price = default(string))
        {
            // to ensure "quoteId" is required (not null)
            this.QuoteId = quoteId ?? throw new ArgumentNullException("quoteId", "quoteId is a required property for InlineResponse20027 and cannot be null");
            // to ensure "validMs" is required (not null)
            this.ValidMs = validMs ?? throw new ArgumentNullException("validMs", "validMs is a required property for InlineResponse20027 and cannot be null");
            // to ensure "fromCoin" is required (not null)
            this.FromCoin = fromCoin ?? throw new ArgumentNullException("fromCoin", "fromCoin is a required property for InlineResponse20027 and cannot be null");
            // to ensure "toCoin" is required (not null)
            this.ToCoin = toCoin ?? throw new ArgumentNullException("toCoin", "toCoin is a required property for InlineResponse20027 and cannot be null");
            // to ensure "fromAmount" is required (not null)
            this.FromAmount = fromAmount ?? throw new ArgumentNullException("fromAmount", "fromAmount is a required property for InlineResponse20027 and cannot be null");
            // to ensure "toAmount" is required (not null)
            this.ToAmount = toAmount ?? throw new ArgumentNullException("toAmount", "toAmount is a required property for InlineResponse20027 and cannot be null");
            // to ensure "price" is required (not null)
            this.Price = price ?? throw new ArgumentNullException("price", "price is a required property for InlineResponse20027 and cannot be null");
        }

        /// <summary>
        /// Quote ID
        /// </summary>
        /// <value>Quote ID</value>
        [DataMember(Name="quote_id")]
        public string QuoteId { get; set; }

        /// <summary>
        /// Valid time (milliseconds timestamp)
        /// </summary>
        /// <value>Valid time (milliseconds timestamp)</value>
        [DataMember(Name="valid_ms")]
        public string ValidMs { get; set; }

        /// <summary>
        /// Asset Sold
        /// </summary>
        /// <value>Asset Sold</value>
        [DataMember(Name="from_coin")]
        public string FromCoin { get; set; }

        /// <summary>
        /// Asset Bought
        /// </summary>
        /// <value>Asset Bought</value>
        [DataMember(Name="to_coin")]
        public string ToCoin { get; set; }

        /// <summary>
        /// Amount to sell
        /// </summary>
        /// <value>Amount to sell</value>
        [DataMember(Name="from_amount")]
        public string FromAmount { get; set; }

        /// <summary>
        /// Amount to buy
        /// </summary>
        /// <value>Amount to buy</value>
        [DataMember(Name="to_amount")]
        public string ToAmount { get; set; }

        /// <summary>
        /// Price
        /// </summary>
        /// <value>Price</value>
        [DataMember(Name="price")]
        public string Price { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20027 {\n");
            sb.Append("  QuoteId: ").Append(QuoteId).Append("\n");
            sb.Append("  ValidMs: ").Append(ValidMs).Append("\n");
            sb.Append("  FromCoin: ").Append(FromCoin).Append("\n");
            sb.Append("  ToCoin: ").Append(ToCoin).Append("\n");
            sb.Append("  FromAmount: ").Append(FromAmount).Append("\n");
            sb.Append("  ToAmount: ").Append(ToAmount).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20027);
        }

        /// <summary>
        /// Returns true if InlineResponse20027 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20027 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20027 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.QuoteId == input.QuoteId ||
                    (this.QuoteId != null &&
                    this.QuoteId.Equals(input.QuoteId))
                ) && 
                (
                    this.ValidMs == input.ValidMs ||
                    (this.ValidMs != null &&
                    this.ValidMs.Equals(input.ValidMs))
                ) && 
                (
                    this.FromCoin == input.FromCoin ||
                    (this.FromCoin != null &&
                    this.FromCoin.Equals(input.FromCoin))
                ) && 
                (
                    this.ToCoin == input.ToCoin ||
                    (this.ToCoin != null &&
                    this.ToCoin.Equals(input.ToCoin))
                ) && 
                (
                    this.FromAmount == input.FromAmount ||
                    (this.FromAmount != null &&
                    this.FromAmount.Equals(input.FromAmount))
                ) && 
                (
                    this.ToAmount == input.ToAmount ||
                    (this.ToAmount != null &&
                    this.ToAmount.Equals(input.ToAmount))
                ) && 
                (
                    this.Price == input.Price ||
                    (this.Price != null &&
                    this.Price.Equals(input.Price))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.QuoteId != null)
                    hashCode = hashCode * 59 + this.QuoteId.GetHashCode();
                if (this.ValidMs != null)
                    hashCode = hashCode * 59 + this.ValidMs.GetHashCode();
                if (this.FromCoin != null)
                    hashCode = hashCode * 59 + this.FromCoin.GetHashCode();
                if (this.ToCoin != null)
                    hashCode = hashCode * 59 + this.ToCoin.GetHashCode();
                if (this.FromAmount != null)
                    hashCode = hashCode * 59 + this.FromAmount.GetHashCode();
                if (this.ToAmount != null)
                    hashCode = hashCode * 59 + this.ToAmount.GetHashCode();
                if (this.Price != null)
                    hashCode = hashCode * 59 + this.Price.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
