/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// InlineResponse20033
    /// </summary>
    [DataContract]
    public partial class InlineResponse20033 :  IEquatable<InlineResponse20033>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20033" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse20033() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse20033" /> class.
        /// </summary>
        /// <param name="userId">User ID (required).</param>
        /// <param name="availableMargin">Available Margin (required).</param>
        /// <param name="marginBalance">marginbalance (required).</param>
        /// <param name="initialMargin">Initial Margin (required).</param>
        /// <param name="maintenanceMargin">Maintenance margin (required).</param>
        /// <param name="initialMarginRate">Initial margin rate (required).</param>
        /// <param name="maintenanceMarginRate">Maintenance margin rate (required).</param>
        /// <param name="positionMode">Contract Position Mode (required).</param>
        /// <param name="accountLimit">Account limit.</param>
        /// <param name="createTime">Created time (required).</param>
        /// <param name="updateTime">Update time (required).</param>
        /// <param name="accountMode">Account Mode. CROSS_EXCHANGE: Cross-Exchange Mode; ISOLATED_EXCHANGE: Split-Exchange Mode.</param>
        /// <param name="exchangeType">Exchange Type. When account_mode is CROSS_EXCHANGE, it must be CROSSEX; otherwise, it is another exchange..</param>
        /// <param name="assets">assets (required).</param>
        public InlineResponse20033(string userId = default(string), string availableMargin = default(string), string marginBalance = default(string), string initialMargin = default(string), string maintenanceMargin = default(string), string initialMarginRate = default(string), string maintenanceMarginRate = default(string), string positionMode = default(string), string accountLimit = default(string), string createTime = default(string), string updateTime = default(string), string accountMode = default(string), string exchangeType = default(string), List<InlineResponse20033Assets> assets = default(List<InlineResponse20033Assets>))
        {
            // to ensure "userId" is required (not null)
            this.UserId = userId ?? throw new ArgumentNullException("userId", "userId is a required property for InlineResponse20033 and cannot be null");
            // to ensure "availableMargin" is required (not null)
            this.AvailableMargin = availableMargin ?? throw new ArgumentNullException("availableMargin", "availableMargin is a required property for InlineResponse20033 and cannot be null");
            // to ensure "marginBalance" is required (not null)
            this.MarginBalance = marginBalance ?? throw new ArgumentNullException("marginBalance", "marginBalance is a required property for InlineResponse20033 and cannot be null");
            // to ensure "initialMargin" is required (not null)
            this.InitialMargin = initialMargin ?? throw new ArgumentNullException("initialMargin", "initialMargin is a required property for InlineResponse20033 and cannot be null");
            // to ensure "maintenanceMargin" is required (not null)
            this.MaintenanceMargin = maintenanceMargin ?? throw new ArgumentNullException("maintenanceMargin", "maintenanceMargin is a required property for InlineResponse20033 and cannot be null");
            // to ensure "initialMarginRate" is required (not null)
            this.InitialMarginRate = initialMarginRate ?? throw new ArgumentNullException("initialMarginRate", "initialMarginRate is a required property for InlineResponse20033 and cannot be null");
            // to ensure "maintenanceMarginRate" is required (not null)
            this.MaintenanceMarginRate = maintenanceMarginRate ?? throw new ArgumentNullException("maintenanceMarginRate", "maintenanceMarginRate is a required property for InlineResponse20033 and cannot be null");
            // to ensure "positionMode" is required (not null)
            this.PositionMode = positionMode ?? throw new ArgumentNullException("positionMode", "positionMode is a required property for InlineResponse20033 and cannot be null");
            // to ensure "createTime" is required (not null)
            this.CreateTime = createTime ?? throw new ArgumentNullException("createTime", "createTime is a required property for InlineResponse20033 and cannot be null");
            // to ensure "updateTime" is required (not null)
            this.UpdateTime = updateTime ?? throw new ArgumentNullException("updateTime", "updateTime is a required property for InlineResponse20033 and cannot be null");
            // to ensure "assets" is required (not null)
            this.Assets = assets ?? throw new ArgumentNullException("assets", "assets is a required property for InlineResponse20033 and cannot be null");
            this.AccountLimit = accountLimit;
            this.AccountMode = accountMode;
            this.ExchangeType = exchangeType;
        }

        /// <summary>
        /// User ID
        /// </summary>
        /// <value>User ID</value>
        [DataMember(Name="user_id")]
        public string UserId { get; set; }

        /// <summary>
        /// Available Margin
        /// </summary>
        /// <value>Available Margin</value>
        [DataMember(Name="available_margin")]
        public string AvailableMargin { get; set; }

        /// <summary>
        /// marginbalance
        /// </summary>
        /// <value>marginbalance</value>
        [DataMember(Name="margin_balance")]
        public string MarginBalance { get; set; }

        /// <summary>
        /// Initial Margin
        /// </summary>
        /// <value>Initial Margin</value>
        [DataMember(Name="initial_margin")]
        public string InitialMargin { get; set; }

        /// <summary>
        /// Maintenance margin
        /// </summary>
        /// <value>Maintenance margin</value>
        [DataMember(Name="maintenance_margin")]
        public string MaintenanceMargin { get; set; }

        /// <summary>
        /// Initial margin rate
        /// </summary>
        /// <value>Initial margin rate</value>
        [DataMember(Name="initial_margin_rate")]
        public string InitialMarginRate { get; set; }

        /// <summary>
        /// Maintenance margin rate
        /// </summary>
        /// <value>Maintenance margin rate</value>
        [DataMember(Name="maintenance_margin_rate")]
        public string MaintenanceMarginRate { get; set; }

        /// <summary>
        /// Contract Position Mode
        /// </summary>
        /// <value>Contract Position Mode</value>
        [DataMember(Name="position_mode")]
        public string PositionMode { get; set; }

        /// <summary>
        /// Account limit
        /// </summary>
        /// <value>Account limit</value>
        [DataMember(Name="account_limit")]
        public string AccountLimit { get; set; }

        /// <summary>
        /// Created time
        /// </summary>
        /// <value>Created time</value>
        [DataMember(Name="create_time")]
        public string CreateTime { get; set; }

        /// <summary>
        /// Update time
        /// </summary>
        /// <value>Update time</value>
        [DataMember(Name="update_time")]
        public string UpdateTime { get; set; }

        /// <summary>
        /// Account Mode. CROSS_EXCHANGE: Cross-Exchange Mode; ISOLATED_EXCHANGE: Split-Exchange Mode
        /// </summary>
        /// <value>Account Mode. CROSS_EXCHANGE: Cross-Exchange Mode; ISOLATED_EXCHANGE: Split-Exchange Mode</value>
        [DataMember(Name="account_mode")]
        public string AccountMode { get; set; }

        /// <summary>
        /// Exchange Type. When account_mode is CROSS_EXCHANGE, it must be CROSSEX; otherwise, it is another exchange.
        /// </summary>
        /// <value>Exchange Type. When account_mode is CROSS_EXCHANGE, it must be CROSSEX; otherwise, it is another exchange.</value>
        [DataMember(Name="exchange_type")]
        public string ExchangeType { get; set; }

        /// <summary>
        /// Gets or Sets Assets
        /// </summary>
        [DataMember(Name="assets")]
        public List<InlineResponse20033Assets> Assets { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse20033 {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  AvailableMargin: ").Append(AvailableMargin).Append("\n");
            sb.Append("  MarginBalance: ").Append(MarginBalance).Append("\n");
            sb.Append("  InitialMargin: ").Append(InitialMargin).Append("\n");
            sb.Append("  MaintenanceMargin: ").Append(MaintenanceMargin).Append("\n");
            sb.Append("  InitialMarginRate: ").Append(InitialMarginRate).Append("\n");
            sb.Append("  MaintenanceMarginRate: ").Append(MaintenanceMarginRate).Append("\n");
            sb.Append("  PositionMode: ").Append(PositionMode).Append("\n");
            sb.Append("  AccountLimit: ").Append(AccountLimit).Append("\n");
            sb.Append("  CreateTime: ").Append(CreateTime).Append("\n");
            sb.Append("  UpdateTime: ").Append(UpdateTime).Append("\n");
            sb.Append("  AccountMode: ").Append(AccountMode).Append("\n");
            sb.Append("  ExchangeType: ").Append(ExchangeType).Append("\n");
            sb.Append("  Assets: ").Append(Assets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse20033);
        }

        /// <summary>
        /// Returns true if InlineResponse20033 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse20033 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse20033 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.AvailableMargin == input.AvailableMargin ||
                    (this.AvailableMargin != null &&
                    this.AvailableMargin.Equals(input.AvailableMargin))
                ) && 
                (
                    this.MarginBalance == input.MarginBalance ||
                    (this.MarginBalance != null &&
                    this.MarginBalance.Equals(input.MarginBalance))
                ) && 
                (
                    this.InitialMargin == input.InitialMargin ||
                    (this.InitialMargin != null &&
                    this.InitialMargin.Equals(input.InitialMargin))
                ) && 
                (
                    this.MaintenanceMargin == input.MaintenanceMargin ||
                    (this.MaintenanceMargin != null &&
                    this.MaintenanceMargin.Equals(input.MaintenanceMargin))
                ) && 
                (
                    this.InitialMarginRate == input.InitialMarginRate ||
                    (this.InitialMarginRate != null &&
                    this.InitialMarginRate.Equals(input.InitialMarginRate))
                ) && 
                (
                    this.MaintenanceMarginRate == input.MaintenanceMarginRate ||
                    (this.MaintenanceMarginRate != null &&
                    this.MaintenanceMarginRate.Equals(input.MaintenanceMarginRate))
                ) && 
                (
                    this.PositionMode == input.PositionMode ||
                    (this.PositionMode != null &&
                    this.PositionMode.Equals(input.PositionMode))
                ) && 
                (
                    this.AccountLimit == input.AccountLimit ||
                    (this.AccountLimit != null &&
                    this.AccountLimit.Equals(input.AccountLimit))
                ) && 
                (
                    this.CreateTime == input.CreateTime ||
                    (this.CreateTime != null &&
                    this.CreateTime.Equals(input.CreateTime))
                ) && 
                (
                    this.UpdateTime == input.UpdateTime ||
                    (this.UpdateTime != null &&
                    this.UpdateTime.Equals(input.UpdateTime))
                ) && 
                (
                    this.AccountMode == input.AccountMode ||
                    (this.AccountMode != null &&
                    this.AccountMode.Equals(input.AccountMode))
                ) && 
                (
                    this.ExchangeType == input.ExchangeType ||
                    (this.ExchangeType != null &&
                    this.ExchangeType.Equals(input.ExchangeType))
                ) && 
                (
                    this.Assets == input.Assets ||
                    this.Assets != null &&
                    input.Assets != null &&
                    this.Assets.SequenceEqual(input.Assets)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.AvailableMargin != null)
                    hashCode = hashCode * 59 + this.AvailableMargin.GetHashCode();
                if (this.MarginBalance != null)
                    hashCode = hashCode * 59 + this.MarginBalance.GetHashCode();
                if (this.InitialMargin != null)
                    hashCode = hashCode * 59 + this.InitialMargin.GetHashCode();
                if (this.MaintenanceMargin != null)
                    hashCode = hashCode * 59 + this.MaintenanceMargin.GetHashCode();
                if (this.InitialMarginRate != null)
                    hashCode = hashCode * 59 + this.InitialMarginRate.GetHashCode();
                if (this.MaintenanceMarginRate != null)
                    hashCode = hashCode * 59 + this.MaintenanceMarginRate.GetHashCode();
                if (this.PositionMode != null)
                    hashCode = hashCode * 59 + this.PositionMode.GetHashCode();
                if (this.AccountLimit != null)
                    hashCode = hashCode * 59 + this.AccountLimit.GetHashCode();
                if (this.CreateTime != null)
                    hashCode = hashCode * 59 + this.CreateTime.GetHashCode();
                if (this.UpdateTime != null)
                    hashCode = hashCode * 59 + this.UpdateTime.GetHashCode();
                if (this.AccountMode != null)
                    hashCode = hashCode * 59 + this.AccountMode.GetHashCode();
                if (this.ExchangeType != null)
                    hashCode = hashCode * 59 + this.ExchangeType.GetHashCode();
                if (this.Assets != null)
                    hashCode = hashCode * 59 + this.Assets.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
