/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// LaunchPoolV4Project
    /// </summary>
    [DataContract]
    public partial class LaunchPoolV4Project :  IEquatable<LaunchPoolV4Project>, IValidatableObject
    {
        /// <summary>
        /// Project status: 1 for ongoing, 2 for warming up, 3 for ended
        /// </summary>
        /// <value>Project status: 1 for ongoing, 2 for warming up, 3 for ended</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProjectStateEnum
        {
            /// <summary>
            /// Enum value NUMBER_1
            /// </summary>
            NUMBER_1 = 1,

            /// <summary>
            /// Enum value NUMBER_2
            /// </summary>
            NUMBER_2 = 2,

            /// <summary>
            /// Enum value NUMBER_3
            /// </summary>
            NUMBER_3 = 3

        }

        /// <summary>
        /// Project status: 1 for ongoing, 2 for warming up, 3 for ended
        /// </summary>
        /// <value>Project status: 1 for ongoing, 2 for warming up, 3 for ended</value>
        [DataMember(Name="project_state")]
        public ProjectStateEnum ProjectState { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchPoolV4Project" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LaunchPoolV4Project() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchPoolV4Project" /> class.
        /// </summary>
        /// <param name="pid">Product ID (required).</param>
        /// <param name="name">Product Name (required).</param>
        /// <param name="totalAmount">Total rewards (required).</param>
        /// <param name="startTimest">Project start timestamp (required).</param>
        /// <param name="endTimest">Project end timestamp (required).</param>
        /// <param name="days">Staking period (in days) (required).</param>
        /// <param name="projectState">Project status: 1 for ongoing, 2 for warming up, 3 for ended (required).</param>
        /// <param name="rewardPools">Collateral currency list (required).</param>
        public LaunchPoolV4Project(int pid = default(int), string name = default(string), string totalAmount = default(string), int startTimest = default(int), int endTimest = default(int), int days = default(int), ProjectStateEnum projectState = default(ProjectStateEnum), List<LaunchPoolV4RewardPool> rewardPools = default(List<LaunchPoolV4RewardPool>))
        {
            this.Pid = pid;
            // to ensure "name" is required (not null)
            this.Name = name ?? throw new ArgumentNullException("name", "name is a required property for LaunchPoolV4Project and cannot be null");
            // to ensure "totalAmount" is required (not null)
            this.TotalAmount = totalAmount ?? throw new ArgumentNullException("totalAmount", "totalAmount is a required property for LaunchPoolV4Project and cannot be null");
            this.StartTimest = startTimest;
            this.EndTimest = endTimest;
            this.Days = days;
            this.ProjectState = projectState;
            // to ensure "rewardPools" is required (not null)
            this.RewardPools = rewardPools ?? throw new ArgumentNullException("rewardPools", "rewardPools is a required property for LaunchPoolV4Project and cannot be null");
        }

        /// <summary>
        /// Product ID
        /// </summary>
        /// <value>Product ID</value>
        [DataMember(Name="pid")]
        public int Pid { get; set; }

        /// <summary>
        /// Product Name
        /// </summary>
        /// <value>Product Name</value>
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Total rewards
        /// </summary>
        /// <value>Total rewards</value>
        [DataMember(Name="total_amount")]
        public string TotalAmount { get; set; }

        /// <summary>
        /// Project start timestamp
        /// </summary>
        /// <value>Project start timestamp</value>
        [DataMember(Name="start_timest")]
        public int StartTimest { get; set; }

        /// <summary>
        /// Project end timestamp
        /// </summary>
        /// <value>Project end timestamp</value>
        [DataMember(Name="end_timest")]
        public int EndTimest { get; set; }

        /// <summary>
        /// Staking period (in days)
        /// </summary>
        /// <value>Staking period (in days)</value>
        [DataMember(Name="days")]
        public int Days { get; set; }

        /// <summary>
        /// Collateral currency list
        /// </summary>
        /// <value>Collateral currency list</value>
        [DataMember(Name="reward_pools")]
        public List<LaunchPoolV4RewardPool> RewardPools { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LaunchPoolV4Project {\n");
            sb.Append("  Pid: ").Append(Pid).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("  StartTimest: ").Append(StartTimest).Append("\n");
            sb.Append("  EndTimest: ").Append(EndTimest).Append("\n");
            sb.Append("  Days: ").Append(Days).Append("\n");
            sb.Append("  ProjectState: ").Append(ProjectState).Append("\n");
            sb.Append("  RewardPools: ").Append(RewardPools).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LaunchPoolV4Project);
        }

        /// <summary>
        /// Returns true if LaunchPoolV4Project instances are equal
        /// </summary>
        /// <param name="input">Instance of LaunchPoolV4Project to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LaunchPoolV4Project input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Pid == input.Pid ||
                    this.Pid.Equals(input.Pid)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.TotalAmount == input.TotalAmount ||
                    (this.TotalAmount != null &&
                    this.TotalAmount.Equals(input.TotalAmount))
                ) && 
                (
                    this.StartTimest == input.StartTimest ||
                    this.StartTimest.Equals(input.StartTimest)
                ) && 
                (
                    this.EndTimest == input.EndTimest ||
                    this.EndTimest.Equals(input.EndTimest)
                ) && 
                (
                    this.Days == input.Days ||
                    this.Days.Equals(input.Days)
                ) && 
                (
                    this.ProjectState == input.ProjectState ||
                    this.ProjectState.Equals(input.ProjectState)
                ) && 
                (
                    this.RewardPools == input.RewardPools ||
                    this.RewardPools != null &&
                    input.RewardPools != null &&
                    this.RewardPools.SequenceEqual(input.RewardPools)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Pid.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.TotalAmount != null)
                    hashCode = hashCode * 59 + this.TotalAmount.GetHashCode();
                hashCode = hashCode * 59 + this.StartTimest.GetHashCode();
                hashCode = hashCode * 59 + this.EndTimest.GetHashCode();
                hashCode = hashCode * 59 + this.Days.GetHashCode();
                hashCode = hashCode * 59 + this.ProjectState.GetHashCode();
                if (this.RewardPools != null)
                    hashCode = hashCode * 59 + this.RewardPools.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
