/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// LaunchPoolV4CreateOrderResponse
    /// </summary>
    [DataContract]
    public partial class LaunchPoolV4CreateOrderResponse :  IEquatable<LaunchPoolV4CreateOrderResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchPoolV4CreateOrderResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LaunchPoolV4CreateOrderResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchPoolV4CreateOrderResponse" /> class.
        /// </summary>
        /// <param name="flowId">Order ID (required).</param>
        public LaunchPoolV4CreateOrderResponse(int flowId = default(int))
        {
            this.FlowId = flowId;
        }

        /// <summary>
        /// Order ID
        /// </summary>
        /// <value>Order ID</value>
        [DataMember(Name="flow_id")]
        public int FlowId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LaunchPoolV4CreateOrderResponse {\n");
            sb.Append("  FlowId: ").Append(FlowId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LaunchPoolV4CreateOrderResponse);
        }

        /// <summary>
        /// Returns true if LaunchPoolV4CreateOrderResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of LaunchPoolV4CreateOrderResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LaunchPoolV4CreateOrderResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FlowId == input.FlowId ||
                    this.FlowId.Equals(input.FlowId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.FlowId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
