/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// OtcBankSupplementChecklistItem
    /// </summary>
    [DataContract]
    public partial class OtcBankSupplementChecklistItem :  IEquatable<OtcBankSupplementChecklistItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OtcBankSupplementChecklistItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OtcBankSupplementChecklistItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OtcBankSupplementChecklistItem" /> class.
        /// </summary>
        /// <param name="code">Material item code, corresponding to the top-level key of &#x60;relationship_proof&#x60; (required).</param>
        /// <param name="zh">zh.</param>
        /// <param name="en">en.</param>
        /// <param name="required">Whether required (required).</param>
        public OtcBankSupplementChecklistItem(string code = default(string), string zh = default(string), string en = default(string), bool required = default(bool))
        {
            // to ensure "code" is required (not null)
            this.Code = code ?? throw new ArgumentNullException("code", "code is a required property for OtcBankSupplementChecklistItem and cannot be null");
            this.Required = required;
            this.Zh = zh;
            this.En = en;
        }

        /// <summary>
        /// Material item code, corresponding to the top-level key of &#x60;relationship_proof&#x60;
        /// </summary>
        /// <value>Material item code, corresponding to the top-level key of &#x60;relationship_proof&#x60;</value>
        [DataMember(Name="code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets or Sets Zh
        /// </summary>
        [DataMember(Name="zh")]
        public string Zh { get; set; }

        /// <summary>
        /// Gets or Sets En
        /// </summary>
        [DataMember(Name="en")]
        public string En { get; set; }

        /// <summary>
        /// Whether required
        /// </summary>
        /// <value>Whether required</value>
        [DataMember(Name="required")]
        public bool Required { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OtcBankSupplementChecklistItem {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Zh: ").Append(Zh).Append("\n");
            sb.Append("  En: ").Append(En).Append("\n");
            sb.Append("  Required: ").Append(Required).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OtcBankSupplementChecklistItem);
        }

        /// <summary>
        /// Returns true if OtcBankSupplementChecklistItem instances are equal
        /// </summary>
        /// <param name="input">Instance of OtcBankSupplementChecklistItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OtcBankSupplementChecklistItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.Zh == input.Zh ||
                    (this.Zh != null &&
                    this.Zh.Equals(input.Zh))
                ) && 
                (
                    this.En == input.En ||
                    (this.En != null &&
                    this.En.Equals(input.En))
                ) && 
                (
                    this.Required == input.Required ||
                    this.Required.Equals(input.Required)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.Zh != null)
                    hashCode = hashCode * 59 + this.Zh.GetHashCode();
                if (this.En != null)
                    hashCode = hashCode * 59 + this.En.GetHashCode();
                hashCode = hashCode * 59 + this.Required.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
