/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// OtcBankIdRequest
    /// </summary>
    [DataContract]
    public partial class OtcBankIdRequest :  IEquatable<OtcBankIdRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OtcBankIdRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OtcBankIdRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OtcBankIdRequest" /> class.
        /// </summary>
        /// <param name="bankId">Bank card ID (required).</param>
        public OtcBankIdRequest(string bankId = default(string))
        {
            // to ensure "bankId" is required (not null)
            this.BankId = bankId ?? throw new ArgumentNullException("bankId", "bankId is a required property for OtcBankIdRequest and cannot be null");
        }

        /// <summary>
        /// Bank card ID
        /// </summary>
        /// <value>Bank card ID</value>
        [DataMember(Name="bank_id")]
        public string BankId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OtcBankIdRequest {\n");
            sb.Append("  BankId: ").Append(BankId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OtcBankIdRequest);
        }

        /// <summary>
        /// Returns true if OtcBankIdRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of OtcBankIdRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OtcBankIdRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BankId == input.BankId ||
                    (this.BankId != null &&
                    this.BankId.Equals(input.BankId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BankId != null)
                    hashCode = hashCode * 59 + this.BankId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
