/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// OtcOrderListItem
    /// </summary>
    [DataContract]
    public partial class OtcOrderListItem :  IEquatable<OtcOrderListItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OtcOrderListItem" /> class.
        /// </summary>
        /// <param name="time">Current time.</param>
        /// <param name="timestamp">Current timestamp.</param>
        /// <param name="orderId">orderId.</param>
        /// <param name="tradeNo">Trade number.</param>
        /// <param name="type">BUY deposit / SELL withdrawal.</param>
        /// <param name="status">Order status.</param>
        /// <param name="fiatCurrency">Fiat currency.</param>
        /// <param name="fiatCurrencyInfo">fiatCurrencyInfo.</param>
        /// <param name="fiatAmount">Fiat amount.</param>
        /// <param name="cryptoCurrency">Digital currency.</param>
        /// <param name="cryptoCurrencyInfo">cryptoCurrencyInfo.</param>
        /// <param name="cryptoAmount">Cryptocurrency amount.</param>
        /// <param name="rate">Exchange rate.</param>
        /// <param name="promotionCode">Promotion code.</param>
        public OtcOrderListItem(string time = default(string), int timestamp = default(int), string orderId = default(string), string tradeNo = default(string), string type = default(string), string status = default(string), string fiatCurrency = default(string), OtcOrderListFiatCurrencyInfo fiatCurrencyInfo = default(OtcOrderListFiatCurrencyInfo), string fiatAmount = default(string), string cryptoCurrency = default(string), OtcOrderListCryptoCurrencyInfo cryptoCurrencyInfo = default(OtcOrderListCryptoCurrencyInfo), string cryptoAmount = default(string), string rate = default(string), string promotionCode = default(string))
        {
            this.Time = time;
            this.Timestamp = timestamp;
            this.OrderId = orderId;
            this.TradeNo = tradeNo;
            this.Type = type;
            this.Status = status;
            this.FiatCurrency = fiatCurrency;
            this.FiatCurrencyInfo = fiatCurrencyInfo;
            this.FiatAmount = fiatAmount;
            this.CryptoCurrency = cryptoCurrency;
            this.CryptoCurrencyInfo = cryptoCurrencyInfo;
            this.CryptoAmount = cryptoAmount;
            this.Rate = rate;
            this.PromotionCode = promotionCode;
        }

        /// <summary>
        /// Current time
        /// </summary>
        /// <value>Current time</value>
        [DataMember(Name="time")]
        public string Time { get; set; }

        /// <summary>
        /// Current timestamp
        /// </summary>
        /// <value>Current timestamp</value>
        [DataMember(Name="timestamp")]
        public int Timestamp { get; set; }

        /// <summary>
        /// orderId
        /// </summary>
        /// <value>orderId</value>
        [DataMember(Name="order_id")]
        public string OrderId { get; set; }

        /// <summary>
        /// Trade number
        /// </summary>
        /// <value>Trade number</value>
        [DataMember(Name="trade_no")]
        public string TradeNo { get; set; }

        /// <summary>
        /// BUY deposit / SELL withdrawal
        /// </summary>
        /// <value>BUY deposit / SELL withdrawal</value>
        [DataMember(Name="type")]
        public string Type { get; set; }

        /// <summary>
        /// Order status
        /// </summary>
        /// <value>Order status</value>
        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// Fiat currency
        /// </summary>
        /// <value>Fiat currency</value>
        [DataMember(Name="fiat_currency")]
        public string FiatCurrency { get; set; }

        /// <summary>
        /// Gets or Sets FiatCurrencyInfo
        /// </summary>
        [DataMember(Name="fiat_currency_info")]
        public OtcOrderListFiatCurrencyInfo FiatCurrencyInfo { get; set; }

        /// <summary>
        /// Fiat amount
        /// </summary>
        /// <value>Fiat amount</value>
        [DataMember(Name="fiat_amount")]
        public string FiatAmount { get; set; }

        /// <summary>
        /// Digital currency
        /// </summary>
        /// <value>Digital currency</value>
        [DataMember(Name="crypto_currency")]
        public string CryptoCurrency { get; set; }

        /// <summary>
        /// Gets or Sets CryptoCurrencyInfo
        /// </summary>
        [DataMember(Name="crypto_currency_info")]
        public OtcOrderListCryptoCurrencyInfo CryptoCurrencyInfo { get; set; }

        /// <summary>
        /// Cryptocurrency amount
        /// </summary>
        /// <value>Cryptocurrency amount</value>
        [DataMember(Name="crypto_amount")]
        public string CryptoAmount { get; set; }

        /// <summary>
        /// Exchange rate
        /// </summary>
        /// <value>Exchange rate</value>
        [DataMember(Name="rate")]
        public string Rate { get; set; }

        /// <summary>
        /// Promotion code
        /// </summary>
        /// <value>Promotion code</value>
        [DataMember(Name="promotion_code")]
        public string PromotionCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OtcOrderListItem {\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  TradeNo: ").Append(TradeNo).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  FiatCurrency: ").Append(FiatCurrency).Append("\n");
            sb.Append("  FiatCurrencyInfo: ").Append(FiatCurrencyInfo).Append("\n");
            sb.Append("  FiatAmount: ").Append(FiatAmount).Append("\n");
            sb.Append("  CryptoCurrency: ").Append(CryptoCurrency).Append("\n");
            sb.Append("  CryptoCurrencyInfo: ").Append(CryptoCurrencyInfo).Append("\n");
            sb.Append("  CryptoAmount: ").Append(CryptoAmount).Append("\n");
            sb.Append("  Rate: ").Append(Rate).Append("\n");
            sb.Append("  PromotionCode: ").Append(PromotionCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OtcOrderListItem);
        }

        /// <summary>
        /// Returns true if OtcOrderListItem instances are equal
        /// </summary>
        /// <param name="input">Instance of OtcOrderListItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OtcOrderListItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Time == input.Time ||
                    (this.Time != null &&
                    this.Time.Equals(input.Time))
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    this.Timestamp.Equals(input.Timestamp)
                ) && 
                (
                    this.OrderId == input.OrderId ||
                    (this.OrderId != null &&
                    this.OrderId.Equals(input.OrderId))
                ) && 
                (
                    this.TradeNo == input.TradeNo ||
                    (this.TradeNo != null &&
                    this.TradeNo.Equals(input.TradeNo))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.FiatCurrency == input.FiatCurrency ||
                    (this.FiatCurrency != null &&
                    this.FiatCurrency.Equals(input.FiatCurrency))
                ) && 
                (
                    this.FiatCurrencyInfo == input.FiatCurrencyInfo ||
                    (this.FiatCurrencyInfo != null &&
                    this.FiatCurrencyInfo.Equals(input.FiatCurrencyInfo))
                ) && 
                (
                    this.FiatAmount == input.FiatAmount ||
                    (this.FiatAmount != null &&
                    this.FiatAmount.Equals(input.FiatAmount))
                ) && 
                (
                    this.CryptoCurrency == input.CryptoCurrency ||
                    (this.CryptoCurrency != null &&
                    this.CryptoCurrency.Equals(input.CryptoCurrency))
                ) && 
                (
                    this.CryptoCurrencyInfo == input.CryptoCurrencyInfo ||
                    (this.CryptoCurrencyInfo != null &&
                    this.CryptoCurrencyInfo.Equals(input.CryptoCurrencyInfo))
                ) && 
                (
                    this.CryptoAmount == input.CryptoAmount ||
                    (this.CryptoAmount != null &&
                    this.CryptoAmount.Equals(input.CryptoAmount))
                ) && 
                (
                    this.Rate == input.Rate ||
                    (this.Rate != null &&
                    this.Rate.Equals(input.Rate))
                ) && 
                (
                    this.PromotionCode == input.PromotionCode ||
                    (this.PromotionCode != null &&
                    this.PromotionCode.Equals(input.PromotionCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Time != null)
                    hashCode = hashCode * 59 + this.Time.GetHashCode();
                hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                if (this.OrderId != null)
                    hashCode = hashCode * 59 + this.OrderId.GetHashCode();
                if (this.TradeNo != null)
                    hashCode = hashCode * 59 + this.TradeNo.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.FiatCurrency != null)
                    hashCode = hashCode * 59 + this.FiatCurrency.GetHashCode();
                if (this.FiatCurrencyInfo != null)
                    hashCode = hashCode * 59 + this.FiatCurrencyInfo.GetHashCode();
                if (this.FiatAmount != null)
                    hashCode = hashCode * 59 + this.FiatAmount.GetHashCode();
                if (this.CryptoCurrency != null)
                    hashCode = hashCode * 59 + this.CryptoCurrency.GetHashCode();
                if (this.CryptoCurrencyInfo != null)
                    hashCode = hashCode * 59 + this.CryptoCurrencyInfo.GetHashCode();
                if (this.CryptoAmount != null)
                    hashCode = hashCode * 59 + this.CryptoAmount.GetHashCode();
                if (this.Rate != null)
                    hashCode = hashCode * 59 + this.Rate.GetHashCode();
                if (this.PromotionCode != null)
                    hashCode = hashCode * 59 + this.PromotionCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
