/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// Flash swap order information
    /// </summary>
    [DataContract]
    public partial class P2pTransactionConvertInfo :  IEquatable<P2pTransactionConvertInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="P2pTransactionConvertInfo" /> class.
        /// </summary>
        /// <param name="convertType">Flash swap target currency.</param>
        /// <param name="convertStatus">Flash swap order status.</param>
        /// <param name="preRate">Expected price when placing order.</param>
        /// <param name="rate">Execution price.</param>
        /// <param name="preFiatRate">Expected fiat price when placing order.</param>
        /// <param name="fiatRate">Fiat price at execution.</param>
        /// <param name="amount">Size.</param>
        /// <param name="convertAmount">Swap Amount.</param>
        /// <param name="slippage">Slippage calculation: slippage &#x3D; (expected price when placing order - real-time price during auto swap) / expected price when placing order.</param>
        /// <param name="status">Flash swap order display status.</param>
        public P2pTransactionConvertInfo(string convertType = default(string), string convertStatus = default(string), string preRate = default(string), string rate = default(string), string preFiatRate = default(string), string fiatRate = default(string), string amount = default(string), string convertAmount = default(string), string slippage = default(string), string status = default(string))
        {
            this.ConvertType = convertType;
            this.ConvertStatus = convertStatus;
            this.PreRate = preRate;
            this.Rate = rate;
            this.PreFiatRate = preFiatRate;
            this.FiatRate = fiatRate;
            this.Amount = amount;
            this.ConvertAmount = convertAmount;
            this.Slippage = slippage;
            this.Status = status;
        }

        /// <summary>
        /// Flash swap target currency
        /// </summary>
        /// <value>Flash swap target currency</value>
        [DataMember(Name="convert_type")]
        public string ConvertType { get; set; }

        /// <summary>
        /// Flash swap order status
        /// </summary>
        /// <value>Flash swap order status</value>
        [DataMember(Name="convert_status")]
        public string ConvertStatus { get; set; }

        /// <summary>
        /// Expected price when placing order
        /// </summary>
        /// <value>Expected price when placing order</value>
        [DataMember(Name="pre_rate")]
        public string PreRate { get; set; }

        /// <summary>
        /// Execution price
        /// </summary>
        /// <value>Execution price</value>
        [DataMember(Name="rate")]
        public string Rate { get; set; }

        /// <summary>
        /// Expected fiat price when placing order
        /// </summary>
        /// <value>Expected fiat price when placing order</value>
        [DataMember(Name="pre_fiat_rate")]
        public string PreFiatRate { get; set; }

        /// <summary>
        /// Fiat price at execution
        /// </summary>
        /// <value>Fiat price at execution</value>
        [DataMember(Name="fiat_rate")]
        public string FiatRate { get; set; }

        /// <summary>
        /// Size
        /// </summary>
        /// <value>Size</value>
        [DataMember(Name="amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Swap Amount
        /// </summary>
        /// <value>Swap Amount</value>
        [DataMember(Name="convert_amount")]
        public string ConvertAmount { get; set; }

        /// <summary>
        /// Slippage calculation: slippage &#x3D; (expected price when placing order - real-time price during auto swap) / expected price when placing order
        /// </summary>
        /// <value>Slippage calculation: slippage &#x3D; (expected price when placing order - real-time price during auto swap) / expected price when placing order</value>
        [DataMember(Name="slippage")]
        public string Slippage { get; set; }

        /// <summary>
        /// Flash swap order display status
        /// </summary>
        /// <value>Flash swap order display status</value>
        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class P2pTransactionConvertInfo {\n");
            sb.Append("  ConvertType: ").Append(ConvertType).Append("\n");
            sb.Append("  ConvertStatus: ").Append(ConvertStatus).Append("\n");
            sb.Append("  PreRate: ").Append(PreRate).Append("\n");
            sb.Append("  Rate: ").Append(Rate).Append("\n");
            sb.Append("  PreFiatRate: ").Append(PreFiatRate).Append("\n");
            sb.Append("  FiatRate: ").Append(FiatRate).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  ConvertAmount: ").Append(ConvertAmount).Append("\n");
            sb.Append("  Slippage: ").Append(Slippage).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as P2pTransactionConvertInfo);
        }

        /// <summary>
        /// Returns true if P2pTransactionConvertInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of P2pTransactionConvertInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(P2pTransactionConvertInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ConvertType == input.ConvertType ||
                    (this.ConvertType != null &&
                    this.ConvertType.Equals(input.ConvertType))
                ) && 
                (
                    this.ConvertStatus == input.ConvertStatus ||
                    (this.ConvertStatus != null &&
                    this.ConvertStatus.Equals(input.ConvertStatus))
                ) && 
                (
                    this.PreRate == input.PreRate ||
                    (this.PreRate != null &&
                    this.PreRate.Equals(input.PreRate))
                ) && 
                (
                    this.Rate == input.Rate ||
                    (this.Rate != null &&
                    this.Rate.Equals(input.Rate))
                ) && 
                (
                    this.PreFiatRate == input.PreFiatRate ||
                    (this.PreFiatRate != null &&
                    this.PreFiatRate.Equals(input.PreFiatRate))
                ) && 
                (
                    this.FiatRate == input.FiatRate ||
                    (this.FiatRate != null &&
                    this.FiatRate.Equals(input.FiatRate))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.ConvertAmount == input.ConvertAmount ||
                    (this.ConvertAmount != null &&
                    this.ConvertAmount.Equals(input.ConvertAmount))
                ) && 
                (
                    this.Slippage == input.Slippage ||
                    (this.Slippage != null &&
                    this.Slippage.Equals(input.Slippage))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ConvertType != null)
                    hashCode = hashCode * 59 + this.ConvertType.GetHashCode();
                if (this.ConvertStatus != null)
                    hashCode = hashCode * 59 + this.ConvertStatus.GetHashCode();
                if (this.PreRate != null)
                    hashCode = hashCode * 59 + this.PreRate.GetHashCode();
                if (this.Rate != null)
                    hashCode = hashCode * 59 + this.Rate.GetHashCode();
                if (this.PreFiatRate != null)
                    hashCode = hashCode * 59 + this.PreFiatRate.GetHashCode();
                if (this.FiatRate != null)
                    hashCode = hashCode * 59 + this.FiatRate.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.ConvertAmount != null)
                    hashCode = hashCode * 59 + this.ConvertAmount.GetHashCode();
                if (this.Slippage != null)
                    hashCode = hashCode * 59 + this.Slippage.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
