/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// Position information
    /// </summary>
    [DataContract]
    public partial class PositionListDataList :  IEquatable<PositionListDataList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PositionListDataList" /> class.
        /// </summary>
        /// <param name="positionId">Position ID.</param>
        /// <param name="symbol">Trading market code.</param>
        /// <param name="symbolDesc">Market description.</param>
        /// <param name="margin">Used margin.</param>
        /// <param name="unrealizedPnl">Unrealized PNL.</param>
        /// <param name="unrealizedPnlRate">Unrealized return rate.</param>
        /// <param name="volume">Position size.</param>
        /// <param name="priceOpen">Average Opening Price.</param>
        /// <param name="positionDir">Position direction (Long&#x3D;long position, Short&#x3D;short position).</param>
        public PositionListDataList(int positionId = default(int), string symbol = default(string), string symbolDesc = default(string), string margin = default(string), string unrealizedPnl = default(string), string unrealizedPnlRate = default(string), string volume = default(string), string priceOpen = default(string), string positionDir = default(string))
        {
            this.PositionId = positionId;
            this.Symbol = symbol;
            this.SymbolDesc = symbolDesc;
            this.Margin = margin;
            this.UnrealizedPnl = unrealizedPnl;
            this.UnrealizedPnlRate = unrealizedPnlRate;
            this.Volume = volume;
            this.PriceOpen = priceOpen;
            this.PositionDir = positionDir;
        }

        /// <summary>
        /// Position ID
        /// </summary>
        /// <value>Position ID</value>
        [DataMember(Name="position_id")]
        public int PositionId { get; set; }

        /// <summary>
        /// Trading market code
        /// </summary>
        /// <value>Trading market code</value>
        [DataMember(Name="symbol")]
        public string Symbol { get; set; }

        /// <summary>
        /// Market description
        /// </summary>
        /// <value>Market description</value>
        [DataMember(Name="symbol_desc")]
        public string SymbolDesc { get; set; }

        /// <summary>
        /// Used margin
        /// </summary>
        /// <value>Used margin</value>
        [DataMember(Name="margin")]
        public string Margin { get; set; }

        /// <summary>
        /// Unrealized PNL
        /// </summary>
        /// <value>Unrealized PNL</value>
        [DataMember(Name="unrealized_pnl")]
        public string UnrealizedPnl { get; set; }

        /// <summary>
        /// Unrealized return rate
        /// </summary>
        /// <value>Unrealized return rate</value>
        [DataMember(Name="unrealized_pnl_rate")]
        public string UnrealizedPnlRate { get; set; }

        /// <summary>
        /// Position size
        /// </summary>
        /// <value>Position size</value>
        [DataMember(Name="volume")]
        public string Volume { get; set; }

        /// <summary>
        /// Average Opening Price
        /// </summary>
        /// <value>Average Opening Price</value>
        [DataMember(Name="price_open")]
        public string PriceOpen { get; set; }

        /// <summary>
        /// Position direction (Long&#x3D;long position, Short&#x3D;short position)
        /// </summary>
        /// <value>Position direction (Long&#x3D;long position, Short&#x3D;short position)</value>
        [DataMember(Name="position_dir")]
        public string PositionDir { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PositionListDataList {\n");
            sb.Append("  PositionId: ").Append(PositionId).Append("\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  SymbolDesc: ").Append(SymbolDesc).Append("\n");
            sb.Append("  Margin: ").Append(Margin).Append("\n");
            sb.Append("  UnrealizedPnl: ").Append(UnrealizedPnl).Append("\n");
            sb.Append("  UnrealizedPnlRate: ").Append(UnrealizedPnlRate).Append("\n");
            sb.Append("  Volume: ").Append(Volume).Append("\n");
            sb.Append("  PriceOpen: ").Append(PriceOpen).Append("\n");
            sb.Append("  PositionDir: ").Append(PositionDir).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PositionListDataList);
        }

        /// <summary>
        /// Returns true if PositionListDataList instances are equal
        /// </summary>
        /// <param name="input">Instance of PositionListDataList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PositionListDataList input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PositionId == input.PositionId ||
                    this.PositionId.Equals(input.PositionId)
                ) && 
                (
                    this.Symbol == input.Symbol ||
                    (this.Symbol != null &&
                    this.Symbol.Equals(input.Symbol))
                ) && 
                (
                    this.SymbolDesc == input.SymbolDesc ||
                    (this.SymbolDesc != null &&
                    this.SymbolDesc.Equals(input.SymbolDesc))
                ) && 
                (
                    this.Margin == input.Margin ||
                    (this.Margin != null &&
                    this.Margin.Equals(input.Margin))
                ) && 
                (
                    this.UnrealizedPnl == input.UnrealizedPnl ||
                    (this.UnrealizedPnl != null &&
                    this.UnrealizedPnl.Equals(input.UnrealizedPnl))
                ) && 
                (
                    this.UnrealizedPnlRate == input.UnrealizedPnlRate ||
                    (this.UnrealizedPnlRate != null &&
                    this.UnrealizedPnlRate.Equals(input.UnrealizedPnlRate))
                ) && 
                (
                    this.Volume == input.Volume ||
                    (this.Volume != null &&
                    this.Volume.Equals(input.Volume))
                ) && 
                (
                    this.PriceOpen == input.PriceOpen ||
                    (this.PriceOpen != null &&
                    this.PriceOpen.Equals(input.PriceOpen))
                ) && 
                (
                    this.PositionDir == input.PositionDir ||
                    (this.PositionDir != null &&
                    this.PositionDir.Equals(input.PositionDir))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.PositionId.GetHashCode();
                if (this.Symbol != null)
                    hashCode = hashCode * 59 + this.Symbol.GetHashCode();
                if (this.SymbolDesc != null)
                    hashCode = hashCode * 59 + this.SymbolDesc.GetHashCode();
                if (this.Margin != null)
                    hashCode = hashCode * 59 + this.Margin.GetHashCode();
                if (this.UnrealizedPnl != null)
                    hashCode = hashCode * 59 + this.UnrealizedPnl.GetHashCode();
                if (this.UnrealizedPnlRate != null)
                    hashCode = hashCode * 59 + this.UnrealizedPnlRate.GetHashCode();
                if (this.Volume != null)
                    hashCode = hashCode * 59 + this.Volume.GetHashCode();
                if (this.PriceOpen != null)
                    hashCode = hashCode * 59 + this.PriceOpen.GetHashCode();
                if (this.PositionDir != null)
                    hashCode = hashCode * 59 + this.PositionDir.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
