/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// RecommendV2Scheme
    /// </summary>
    [DataContract]
    public partial class RecommendV2Scheme :  IEquatable<RecommendV2Scheme>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecommendV2Scheme" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RecommendV2Scheme() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RecommendV2Scheme" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="priority">priority (required).</param>
        /// <param name="ratio">ratio (required).</param>
        public RecommendV2Scheme(string name = default(string), int priority = default(int), string ratio = default(string))
        {
            // to ensure "name" is required (not null)
            this.Name = name ?? throw new ArgumentNullException("name", "name is a required property for RecommendV2Scheme and cannot be null");
            this.Priority = priority;
            // to ensure "ratio" is required (not null)
            this.Ratio = ratio ?? throw new ArgumentNullException("ratio", "ratio is a required property for RecommendV2Scheme and cannot be null");
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [DataMember(Name="priority")]
        public int Priority { get; set; }

        /// <summary>
        /// Gets or Sets Ratio
        /// </summary>
        [DataMember(Name="ratio")]
        public string Ratio { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RecommendV2Scheme {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Ratio: ").Append(Ratio).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RecommendV2Scheme);
        }

        /// <summary>
        /// Returns true if RecommendV2Scheme instances are equal
        /// </summary>
        /// <param name="input">Instance of RecommendV2Scheme to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RecommendV2Scheme input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Priority == input.Priority ||
                    this.Priority.Equals(input.Priority)
                ) && 
                (
                    this.Ratio == input.Ratio ||
                    (this.Ratio != null &&
                    this.Ratio.Equals(input.Ratio))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                hashCode = hashCode * 59 + this.Priority.GetHashCode();
                if (this.Ratio != null)
                    hashCode = hashCode * 59 + this.Ratio.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
