/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// Spot POV order details
    /// </summary>
    [DataContract]
    public partial class SpotPovOrder :  IEquatable<SpotPovOrder>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpotPovOrder" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SpotPovOrder() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SpotPovOrder" /> class.
        /// </summary>
        /// <param name="text">Order custom information. Users can set custom ID with this field. Custom fields must meet the following conditions:  1. Must start with &#x60;t-&#x60; 2. Excluding &#x60;t-&#x60;, length cannot exceed 28 bytes 3. Can only contain numbers, letters, underscore(_), hyphen(-) or dot(.) .</param>
        public SpotPovOrder(string text = default(string))
        {
            this.Text = text;
        }

        /// <summary>
        /// Order ID
        /// </summary>
        /// <value>Order ID</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; private set; }

        /// <summary>
        /// Currency pair
        /// </summary>
        /// <value>Currency pair</value>
        [DataMember(Name="currency_pair", EmitDefaultValue=false)]
        public string CurrencyPair { get; private set; }

        /// <summary>
        /// Buy or sell order
        /// </summary>
        /// <value>Buy or sell order</value>
        [DataMember(Name="side", EmitDefaultValue=false)]
        public string Side { get; private set; }

        /// <summary>
        /// Trade amount
        /// </summary>
        /// <value>Trade amount</value>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public string Amount { get; private set; }

        /// <summary>
        /// Target participation rate as a percentage. Allowed values: 5, 10, 20, and 40
        /// </summary>
        /// <value>Target participation rate as a percentage. Allowed values: 5, 10, 20, and 40</value>
        [DataMember(Name="participation_rate", EmitDefaultValue=false)]
        public int ParticipationRate { get; private set; }

        /// <summary>
        /// Time to live. Valid values: 1h, 6h, 12h, 1d, 2d, 3d, 4d, 5d, 6d, and 7d
        /// </summary>
        /// <value>Time to live. Valid values: 1h, 6h, 12h, 1d, 2d, 3d, 4d, 5d, 6d, and 7d</value>
        [DataMember(Name="ttl", EmitDefaultValue=false)]
        public string Ttl { get; private set; }

        /// <summary>
        /// Limit price. If omitted, the market price is used
        /// </summary>
        /// <value>Limit price. If omitted, the market price is used</value>
        [DataMember(Name="limit_price", EmitDefaultValue=false)]
        public string LimitPrice { get; private set; }

        /// <summary>
        /// Trigger price. If omitted, the order is triggered immediately
        /// </summary>
        /// <value>Trigger price. If omitted, the order is triggered immediately</value>
        [DataMember(Name="trigger_price", EmitDefaultValue=false)]
        public string TriggerPrice { get; private set; }

        /// <summary>
        /// Order status  - CREATED: Created - CANCELING: Canceling - RUNNING: Running - COMPLETED: Completed - EXPIRED: Expired - TERMINATED: Terminated
        /// </summary>
        /// <value>Order status  - CREATED: Created - CANCELING: Canceling - RUNNING: Running - COMPLETED: Completed - EXPIRED: Expired - TERMINATED: Terminated</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; private set; }

        /// <summary>
        /// Order termination reason code
        /// </summary>
        /// <value>Order termination reason code</value>
        [DataMember(Name="terminated_as", EmitDefaultValue=false)]
        public string TerminatedAs { get; private set; }

        /// <summary>
        /// Order execution start time in milliseconds
        /// </summary>
        /// <value>Order execution start time in milliseconds</value>
        [DataMember(Name="start_time_ms", EmitDefaultValue=false)]
        public long StartTimeMs { get; private set; }

        /// <summary>
        /// Order execution end time in milliseconds
        /// </summary>
        /// <value>Order execution end time in milliseconds</value>
        [DataMember(Name="end_time_ms", EmitDefaultValue=false)]
        public long EndTimeMs { get; private set; }

        /// <summary>
        /// Order expiration time in milliseconds
        /// </summary>
        /// <value>Order expiration time in milliseconds</value>
        [DataMember(Name="expire_time_ms", EmitDefaultValue=false)]
        public long ExpireTimeMs { get; private set; }

        /// <summary>
        /// Creation time of order (in milliseconds)
        /// </summary>
        /// <value>Creation time of order (in milliseconds)</value>
        [DataMember(Name="create_time_ms", EmitDefaultValue=false)]
        public long CreateTimeMs { get; private set; }

        /// <summary>
        /// Last modification time of order (in milliseconds)
        /// </summary>
        /// <value>Last modification time of order (in milliseconds)</value>
        [DataMember(Name="update_time_ms", EmitDefaultValue=false)]
        public long UpdateTimeMs { get; private set; }

        /// <summary>
        /// Order custom information. Users can set custom ID with this field. Custom fields must meet the following conditions:  1. Must start with &#x60;t-&#x60; 2. Excluding &#x60;t-&#x60;, length cannot exceed 28 bytes 3. Can only contain numbers, letters, underscore(_), hyphen(-) or dot(.) 
        /// </summary>
        /// <value>Order custom information. Users can set custom ID with this field. Custom fields must meet the following conditions:  1. Must start with &#x60;t-&#x60; 2. Excluding &#x60;t-&#x60;, length cannot exceed 28 bytes 3. Can only contain numbers, letters, underscore(_), hyphen(-) or dot(.) </value>
        [DataMember(Name="text")]
        public string Text { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpotPovOrder {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CurrencyPair: ").Append(CurrencyPair).Append("\n");
            sb.Append("  Side: ").Append(Side).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  ParticipationRate: ").Append(ParticipationRate).Append("\n");
            sb.Append("  Ttl: ").Append(Ttl).Append("\n");
            sb.Append("  LimitPrice: ").Append(LimitPrice).Append("\n");
            sb.Append("  TriggerPrice: ").Append(TriggerPrice).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TerminatedAs: ").Append(TerminatedAs).Append("\n");
            sb.Append("  StartTimeMs: ").Append(StartTimeMs).Append("\n");
            sb.Append("  EndTimeMs: ").Append(EndTimeMs).Append("\n");
            sb.Append("  ExpireTimeMs: ").Append(ExpireTimeMs).Append("\n");
            sb.Append("  CreateTimeMs: ").Append(CreateTimeMs).Append("\n");
            sb.Append("  UpdateTimeMs: ").Append(UpdateTimeMs).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpotPovOrder);
        }

        /// <summary>
        /// Returns true if SpotPovOrder instances are equal
        /// </summary>
        /// <param name="input">Instance of SpotPovOrder to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpotPovOrder input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.CurrencyPair == input.CurrencyPair ||
                    (this.CurrencyPair != null &&
                    this.CurrencyPair.Equals(input.CurrencyPair))
                ) && 
                (
                    this.Side == input.Side ||
                    (this.Side != null &&
                    this.Side.Equals(input.Side))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.ParticipationRate == input.ParticipationRate ||
                    this.ParticipationRate.Equals(input.ParticipationRate)
                ) && 
                (
                    this.Ttl == input.Ttl ||
                    (this.Ttl != null &&
                    this.Ttl.Equals(input.Ttl))
                ) && 
                (
                    this.LimitPrice == input.LimitPrice ||
                    (this.LimitPrice != null &&
                    this.LimitPrice.Equals(input.LimitPrice))
                ) && 
                (
                    this.TriggerPrice == input.TriggerPrice ||
                    (this.TriggerPrice != null &&
                    this.TriggerPrice.Equals(input.TriggerPrice))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.TerminatedAs == input.TerminatedAs ||
                    (this.TerminatedAs != null &&
                    this.TerminatedAs.Equals(input.TerminatedAs))
                ) && 
                (
                    this.StartTimeMs == input.StartTimeMs ||
                    this.StartTimeMs.Equals(input.StartTimeMs)
                ) && 
                (
                    this.EndTimeMs == input.EndTimeMs ||
                    this.EndTimeMs.Equals(input.EndTimeMs)
                ) && 
                (
                    this.ExpireTimeMs == input.ExpireTimeMs ||
                    this.ExpireTimeMs.Equals(input.ExpireTimeMs)
                ) && 
                (
                    this.CreateTimeMs == input.CreateTimeMs ||
                    this.CreateTimeMs.Equals(input.CreateTimeMs)
                ) && 
                (
                    this.UpdateTimeMs == input.UpdateTimeMs ||
                    this.UpdateTimeMs.Equals(input.UpdateTimeMs)
                ) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.CurrencyPair != null)
                    hashCode = hashCode * 59 + this.CurrencyPair.GetHashCode();
                if (this.Side != null)
                    hashCode = hashCode * 59 + this.Side.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                hashCode = hashCode * 59 + this.ParticipationRate.GetHashCode();
                if (this.Ttl != null)
                    hashCode = hashCode * 59 + this.Ttl.GetHashCode();
                if (this.LimitPrice != null)
                    hashCode = hashCode * 59 + this.LimitPrice.GetHashCode();
                if (this.TriggerPrice != null)
                    hashCode = hashCode * 59 + this.TriggerPrice.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.TerminatedAs != null)
                    hashCode = hashCode * 59 + this.TerminatedAs.GetHashCode();
                hashCode = hashCode * 59 + this.StartTimeMs.GetHashCode();
                hashCode = hashCode * 59 + this.EndTimeMs.GetHashCode();
                hashCode = hashCode * 59 + this.ExpireTimeMs.GetHashCode();
                hashCode = hashCode * 59 + this.CreateTimeMs.GetHashCode();
                hashCode = hashCode * 59 + this.UpdateTimeMs.GetHashCode();
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
