/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// StopTrailOrder
    /// </summary>
    [DataContract]
    public partial class StopTrailOrder :  IEquatable<StopTrailOrder>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StopTrailOrder" /> class.
        /// </summary>
        /// <param name="id">Order ID, if ID is specified, text is not needed.</param>
        /// <param name="text">Custom text, if ID is not specified, terminate based on user_id and text.</param>
        public StopTrailOrder(long id = default(long), string text = default(string))
        {
            this.Id = id;
            this.Text = text;
        }

        /// <summary>
        /// Order ID, if ID is specified, text is not needed
        /// </summary>
        /// <value>Order ID, if ID is specified, text is not needed</value>
        [DataMember(Name="id")]
        public long Id { get; set; }

        /// <summary>
        /// Custom text, if ID is not specified, terminate based on user_id and text
        /// </summary>
        /// <value>Custom text, if ID is not specified, terminate based on user_id and text</value>
        [DataMember(Name="text")]
        public string Text { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StopTrailOrder {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StopTrailOrder);
        }

        /// <summary>
        /// Returns true if StopTrailOrder instances are equal
        /// </summary>
        /// <param name="input">Instance of StopTrailOrder to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StopTrailOrder input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
