/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// Request body for stopping chase orders in batch
    /// </summary>
    [DataContract]
    public partial class StopAllChaseOrdersReq :  IEquatable<StopAllChaseOrdersReq>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StopAllChaseOrdersReq" /> class.
        /// </summary>
        /// <param name="contract">Optional contract name.</param>
        /// <param name="settle">Overridden by the path parameter.</param>
        /// <param name="posMarginMode">Optional margin mode.</param>
        public StopAllChaseOrdersReq(string contract = default(string), string settle = default(string), string posMarginMode = default(string))
        {
            this.Contract = contract;
            this.Settle = settle;
            this.PosMarginMode = posMarginMode;
        }

        /// <summary>
        /// Optional contract name
        /// </summary>
        /// <value>Optional contract name</value>
        [DataMember(Name="contract")]
        public string Contract { get; set; }

        /// <summary>
        /// Overridden by the path parameter
        /// </summary>
        /// <value>Overridden by the path parameter</value>
        [DataMember(Name="settle")]
        public string Settle { get; set; }

        /// <summary>
        /// Optional margin mode
        /// </summary>
        /// <value>Optional margin mode</value>
        [DataMember(Name="pos_margin_mode")]
        public string PosMarginMode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StopAllChaseOrdersReq {\n");
            sb.Append("  Contract: ").Append(Contract).Append("\n");
            sb.Append("  Settle: ").Append(Settle).Append("\n");
            sb.Append("  PosMarginMode: ").Append(PosMarginMode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StopAllChaseOrdersReq);
        }

        /// <summary>
        /// Returns true if StopAllChaseOrdersReq instances are equal
        /// </summary>
        /// <param name="input">Instance of StopAllChaseOrdersReq to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StopAllChaseOrdersReq input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Contract == input.Contract ||
                    (this.Contract != null &&
                    this.Contract.Equals(input.Contract))
                ) && 
                (
                    this.Settle == input.Settle ||
                    (this.Settle != null &&
                    this.Settle.Equals(input.Settle))
                ) && 
                (
                    this.PosMarginMode == input.PosMarginMode ||
                    (this.PosMarginMode != null &&
                    this.PosMarginMode.Equals(input.PosMarginMode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Contract != null)
                    hashCode = hashCode * 59 + this.Contract.GetHashCode();
                if (this.Settle != null)
                    hashCode = hashCode * 59 + this.Settle.GetHashCode();
                if (this.PosMarginMode != null)
                    hashCode = hashCode * 59 + this.PosMarginMode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
