/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// TransactionList2Data
    /// </summary>
    [DataContract]
    public partial class TransactionList2Data :  IEquatable<TransactionList2Data>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionList2Data" /> class.
        /// </summary>
        /// <param name="total">total.</param>
        /// <param name="totalPage">totalPage.</param>
        /// <param name="list">Transaction record list.</param>
        public TransactionList2Data(long total = default(long), long totalPage = default(long), List<TransactionItem> list = default(List<TransactionItem>))
        {
            this.Total = total;
            this.TotalPage = totalPage;
            this.List = list;
        }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [DataMember(Name="total")]
        public long Total { get; set; }

        /// <summary>
        /// Gets or Sets TotalPage
        /// </summary>
        [DataMember(Name="total_page")]
        public long TotalPage { get; set; }

        /// <summary>
        /// Transaction record list
        /// </summary>
        /// <value>Transaction record list</value>
        [DataMember(Name="list")]
        public List<TransactionItem> List { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionList2Data {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  TotalPage: ").Append(TotalPage).Append("\n");
            sb.Append("  List: ").Append(List).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionList2Data);
        }

        /// <summary>
        /// Returns true if TransactionList2Data instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionList2Data to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionList2Data input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Total == input.Total ||
                    this.Total.Equals(input.Total)
                ) && 
                (
                    this.TotalPage == input.TotalPage ||
                    this.TotalPage.Equals(input.TotalPage)
                ) && 
                (
                    this.List == input.List ||
                    this.List != null &&
                    input.List != null &&
                    this.List.SequenceEqual(input.List)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Total.GetHashCode();
                hashCode = hashCode * 59 + this.TotalPage.GetHashCode();
                if (this.List != null)
                    hashCode = hashCode * 59 + this.List.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
