/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// UnifiedQuickRepayDebtItem
    /// </summary>
    [DataContract]
    public partial class UnifiedQuickRepayDebtItem :  IEquatable<UnifiedQuickRepayDebtItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnifiedQuickRepayDebtItem" /> class.
        /// </summary>
        /// <param name="currency">Currency name.</param>
        /// <param name="debtAmount">Debt Quantity.</param>
        /// <param name="estimatedUsd">Estimated USD value.</param>
        /// <param name="borrowed">Borrowed amount.</param>
        /// <param name="negBalance">Negative balance.</param>
        public UnifiedQuickRepayDebtItem(string currency = default(string), string debtAmount = default(string), string estimatedUsd = default(string), string borrowed = default(string), string negBalance = default(string))
        {
            this.Currency = currency;
            this.DebtAmount = debtAmount;
            this.EstimatedUsd = estimatedUsd;
            this.Borrowed = borrowed;
            this.NegBalance = negBalance;
        }

        /// <summary>
        /// Currency name
        /// </summary>
        /// <value>Currency name</value>
        [DataMember(Name="currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Debt Quantity
        /// </summary>
        /// <value>Debt Quantity</value>
        [DataMember(Name="debt_amount")]
        public string DebtAmount { get; set; }

        /// <summary>
        /// Estimated USD value
        /// </summary>
        /// <value>Estimated USD value</value>
        [DataMember(Name="estimated_usd")]
        public string EstimatedUsd { get; set; }

        /// <summary>
        /// Borrowed amount
        /// </summary>
        /// <value>Borrowed amount</value>
        [DataMember(Name="borrowed")]
        public string Borrowed { get; set; }

        /// <summary>
        /// Negative balance
        /// </summary>
        /// <value>Negative balance</value>
        [DataMember(Name="neg_balance")]
        public string NegBalance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UnifiedQuickRepayDebtItem {\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  DebtAmount: ").Append(DebtAmount).Append("\n");
            sb.Append("  EstimatedUsd: ").Append(EstimatedUsd).Append("\n");
            sb.Append("  Borrowed: ").Append(Borrowed).Append("\n");
            sb.Append("  NegBalance: ").Append(NegBalance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UnifiedQuickRepayDebtItem);
        }

        /// <summary>
        /// Returns true if UnifiedQuickRepayDebtItem instances are equal
        /// </summary>
        /// <param name="input">Instance of UnifiedQuickRepayDebtItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UnifiedQuickRepayDebtItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.DebtAmount == input.DebtAmount ||
                    (this.DebtAmount != null &&
                    this.DebtAmount.Equals(input.DebtAmount))
                ) && 
                (
                    this.EstimatedUsd == input.EstimatedUsd ||
                    (this.EstimatedUsd != null &&
                    this.EstimatedUsd.Equals(input.EstimatedUsd))
                ) && 
                (
                    this.Borrowed == input.Borrowed ||
                    (this.Borrowed != null &&
                    this.Borrowed.Equals(input.Borrowed))
                ) && 
                (
                    this.NegBalance == input.NegBalance ||
                    (this.NegBalance != null &&
                    this.NegBalance.Equals(input.NegBalance))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Currency != null)
                    hashCode = hashCode * 59 + this.Currency.GetHashCode();
                if (this.DebtAmount != null)
                    hashCode = hashCode * 59 + this.DebtAmount.GetHashCode();
                if (this.EstimatedUsd != null)
                    hashCode = hashCode * 59 + this.EstimatedUsd.GetHashCode();
                if (this.Borrowed != null)
                    hashCode = hashCode * 59 + this.Borrowed.GetHashCode();
                if (this.NegBalance != null)
                    hashCode = hashCode * 59 + this.NegBalance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
